/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Lock } from "./Lock";
export type { Solar } from "./Solar";
export * as factories from "./factories";
export type { ISolar } from "./interfaces/ISolar";
export { ISolar__factory } from "./factories/interfaces/ISolar__factory";
export { Lock__factory } from "./factories/Lock__factory";
export { Solar__factory } from "./factories/Solar__factory";
